%% showResult: function description
function [outputs] = showResult(dx, HS, Ec, J, dU, Tr)
	lF = {'$\Delta E_{w} =', '$\Delta E_{w} =', '$\Delta E_{w} =', '$\Delta E_{w} ='}';
	lL = {'$ eV', '$ eV', '$ eV', '$ eV'}';

	Ew = [0.3, 0.7, 1, 1.3];

	figure('units', 'normalized', 'outerposition', [0 0 1 1]);

	Axes = {
		subplot(1, 2, 1);
		subplot(1, 2, 2);
	};

	plot(Axes{1}, (0:HS-1)*dx*1e9, Ec);
	plotFormat( Axes{1}, ...
		'Potential energy' , ...
		'$x$, $nm$', '$E_{c}$, eV', ...
		strcat(lF, strread(num2str(Ew),'%s'), lL), ...
		[0, (HS-1)*dx*1e9], [], ...
		18 ...
	);

	plot(Axes{2}, log(Tr)', (ones(length(Ec(:, 1)), 1)*linspace(0, max(max(Ec)), length(Tr(1, :))))' );
	plotFormat( Axes{2}, ...
		'Transperent of RTHS',...
		'$\ln T(E)$', 'Energy, eV', ...
		strcat(lF, strread(num2str(Ew),'%s'), lL), ...
		[], [], ...
		18 ...
	);
		
	figure('units', 'normalized', 'outerposition', [0 0 1 1]);
	Axes = {
		subplot(2, 2, 1);
		subplot(2, 2, 2);
		subplot(2, 2, 3);
		subplot(2, 2, 4);
	};

	plot(Axes{1}, dU, J(1, :));
	plotFormat( Axes{1}, ...
		strcat('Current density') , ...
		'$dU$, V', '$J$, A/m$^{-2}$', ...
		strcat(lF(1), strread(num2str(Ew(1)),'%s'), lL(1)), ...
		[0, 1], [], ...
		18 ...
	);

	plot(Axes{2}, dU, J(2, :));
	plotFormat( Axes{2}, ...
		strcat('Current density') , ...
		'$dU$, V', '$J$, A/m$^{-2}$', ...
		strcat(lF(2), strread(num2str(Ew(2)),'%s'), lL(2)), ...
		[0, 1], [], ...
		18 ...
	);

	plot(Axes{3}, dU, J(3, :));
	plotFormat( Axes{3}, ...
		strcat('Current density') , ...
		'$dU$, V', '$J$, A/m$^{-2}$', ...
		strcat(lF(2), strread(num2str(Ew(3)),'%s'), lL(2)), ...
		[0, 1], [], ...
		18 ...
	);

	plot(Axes{4}, dU, J(4, :));
	plotFormat( Axes{4}, ...
		strcat('Current density') , ...
		'$dU$, V', '$J$, A/m$^{-2}$', ...
		strcat(lF(2), strread(num2str(Ew(4)),'%s'), lL(2)), ...
		[0, 1], [], ...
		18 ...
	);

	outputs = 1;