%% showResult: function description
function [outputs] = showResult(dx, HS, J1, J2, J3, J4, J5, J6, J7, J8, dU, b)
	lF = {'$Spacer =', '$Spacer =', '$Spacer =', '$Spacer =', '$Spacer =', '$Spacer =', '$Spacer =', '$Spacer ='}';
	lL = {'$, monolayers', '$, monolayers', '$, monolayers', '$, monolayers', '$, monolayers', '$, monolayers', '$, monolayers', '$, monolayers'}';
		
	figure('units', 'normalized', 'outerposition', [0 0 1 1]);
	Axes = {
		subplot(1, 2, 1);
		subplot(1, 2, 2);
	};

	plot(Axes{1}, dU, J1, dU, J2, dU, J3, dU, J4);
	plotFormat( Axes{1}, ...
		strcat('Current density') , ...
		'$dU$, V', '$J$, A/m$^{-2}$',...
		strcat(lF(1:4), strread(num2str(b(1:4)),'%s'), lL(1:4)), ...
		[], [], ...
		18 ...
	);

	plot(Axes{2}, dU, J5, dU, J6, dU, J7, dU, J8 );
	plotFormat( Axes{2}, ...
		strcat('Current density') , ...
		'$dU$, V', '$J$, A/m$^{-2}$',...
		strcat(lF(5:8), strread(num2str(b(5:8)),'%s'), lL(5:8)), ...
		[], [], ...
		18 ...
	);

	figure('units', 'normalized', 'outerposition', [0 0 1 1]);
	Axes = {
		subplot(1, 1, 1);
	};

	plot(Axes{1}, dU, J1, dU, J2, dU, J3, dU, J4, dU, J5, dU, J6, dU, J7, dU, J8);
	plotFormat( Axes{1}, ...
		strcat('Current density') , ...
		'$dU$, V', '$J$, A/m$^{-2}$',...
		strcat(lF(1:8), strread(num2str(b(1:8)),'%s'), lL(1:8)), ...
		[], [], ...
		18 ...
	);

	outputs = 1;