%% showResult: function description
function [outputs] = showResult(dx, HS, Ec, J, dU, Tr)
	lF = {'$\Delta U_{b} =', '$\Delta U_{b} =', '$\Delta U_{b} =', '$\Delta U_{b} ='}';
	lL = {'$ eV', '$ eV', '$ eV', '$ eV'}';

	figure('units', 'normalized', 'outerposition', [0 0 1 1]);

	Axes = {
		subplot(1, 2, 1);
		subplot(1, 2, 2);
	};

	plot(Axes{1}, (0:HS-1)*dx*1e9, Ec);
	plotFormat( Axes{1}, ...
		'Potential energy' , ...
		'$x$, $nm$', '$E_{c}$, eV', ...
		strcat(lF, strread(num2str(max(Ec')),'%s'), lL), ...
		[0, (HS-1)*dx*1e9], [], ...
		18 ...
	);

	plot(Axes{2}, log(Tr)', (ones(length(Ec(:, 1)), 1)*linspace(0, max(max(Ec)), length(Tr(1, :))))' );
	plotFormat( Axes{2}, ...
		'Transperent of RTHS',...
		'$\ln T(E)$', 'Energy, eV', ...
		strcat(lF, strread(num2str(max(Ec')),'%s'), lL), ...
		[], [], ...
		18 ...
	);
		
	figure('units', 'normalized', 'outerposition', [0 0 1 1]);
	Axes = {
		subplot(1, 2, 1);
		subplot(1, 2, 2);
	};

	plot(Axes{1}, dU, J(1:2, :));
	plotFormat( Axes{1}, ...
		strcat('Current density') , ...
		 '$dU$, V', '$J$, A/m$^{-2}$',...
		strcat(lF(1:2), strread(num2str(max(Ec(1:2, :)')),'%s'), lL(1:2)), ...
		[], [], ...
		18 ...
	);

	plot(Axes{2}, dU, J(3:4, :));
	plotFormat( Axes{2}, ...
		strcat('Current density') , ...
		 '$dU$, V', '$J$, A/m$^{-2}$',...
		strcat(lF(1:2), strread(num2str(max(Ec(3:4, :)')),'%s'), lL(1:2)), ...
		[0, 0.4], [], ...
		18 ...
	);

	outputs = 1;