%% showResult: function description
function [outputs] = showResult(dx, HS, xAl, Title, checkTime)
	figure('units', 'normalized', 'outerposition', [0 0 1 1]);
	Axes = {
		subplot(1, 1, 1);
	};

	plot(Axes{1}, (0:HS-1)*dx, xAl);
	plotFormat( Axes{1}, ...
		strcat('Part of Aluminum in', Title) , ...
		'z, $nm$', 'x, part of Al', ...
		strread(num2str(checkTime),'%s'), ...
		[0, (HS-1)*dx], [], ...
		16 ...
	);
end