%% showResult: function description
function [outResult] = showResult(grids_C_Al, grids_Ec, checkTime, sizeHS, dx, T, dU)
figure('units', 'normalized', 'outerposition', [0 0 1 1]);
Axes = {
	subplot(1, 2, 1);
	subplot(1, 2, 2);
};
checkTime = checkTime/24/360;

lF = {'$t =', '$t =', '$t =', '$t ='}';
lL = {'$ years', '$ years', '$ years', '$ years'}';

plot(Axes{1}, (0:sizeHS-1)*dx, grids_C_Al);
plotFormat( Axes{1}, ...
	strcat('Part of Aluminum, then $T=', num2str(T),'K$'), ...
	'z, $nm$', 'x, part of Al', ...
	strcat(lF, strread(num2str(checkTime),'%s'), lL), ...
	[0, (sizeHS-1)*dx], [], ...
	16 ...
);

plot(Axes{2}, (0:sizeHS-1)*dx, grids_Ec);
plotFormat( Axes{2}, ...
	strcat('$E_{c}$, then $T=', num2str(T),'K$') , ...
	'z, $nm$', 'Energy, eV', ...
	strcat(lF, strread(num2str(checkTime),'%s'), lL), ...
	[0, (sizeHS-1)*dx], [], ...
	16 ...
);
outResult = 1
end