%% showResult: function description
function [outputs] = showResult(dx, EcRTHS, EcBHS, JBHS, JRTHS, TrBHS, TrRTHS, dU)

	figure('units', 'normalized', 'outerposition', [0 0 1 1]);
	Axes = {
		subplot(1, 2, 1);
		subplot(1, 2, 2);
	};

	plot(Axes{1},...
		log(TrBHS), linspace(0, max(max(EcBHS)), length(TrBHS)));

	plotFormat( Axes{1}, ...
		'Transperent of BHS',...
		'$\ln T(E)$', 'Energy, eV', ...
		{}, ...
		[], [], ...
		18 ...
	);

	plot(Axes{2}, dU, JBHS);
	plotFormat( Axes{2}, ...
		strcat('Current density of BHS') , ...
		'$dU$, V', '$J$, A/m$^{-2}$', ...
		{}, ...
		[], [], ...
		18 ...
	);


	figure('units', 'normalized', 'outerposition', [0 0 1 1]);
	Axes = {
		subplot(1, 2, 1);
		subplot(1, 2, 2);
	};

	plot(Axes{1},...
		log(TrRTHS), linspace(0, max(max(EcRTHS)), length(TrRTHS)));
	plotFormat( Axes{1}, ...
		'Transperent of RTHS',...
		'$\ln T(E)$', 'Energy, eV', ...
		{}, ...
		[], [], ...
		18 ...
	);

	plot(Axes{2}, dU, JRTHS);
	plotFormat( Axes{2}, ...
		strcat('Current density of RTHS') , ...
		'$dU$, V', '$J$, A/m$^{-2}$',...
		{}, ...
		[], [], ...
		18 ...
	);

	outputs = 1;