%% showResult: function description
function [outResult] = showResult(grids_C_Al, grids_C_Si, grids_Ec, checkTime, J, sizeHS, dx, T, dU, Nd)
figure('units', 'normalized', 'outerposition', [0 0 1 1]);
Axes = {
	subplot(1, 2, 1);
	subplot(1, 2, 2);
};

plot(Axes{1}, (0:sizeHS-1)*dx, grids_C_Al);
plotFormat( Axes{1}, ...
	strcat('$E_{c}$, then $T=', num2str(T),'K$, $N_{D}=', num2str(Nd), '\,1/m^{-3}$') , ...
	'z, $nm$', 'Energy, eV', ...
	strread(num2str(checkTime),'%s'), ...
	[0, (sizeHS-1)*dx], [], ...
	16 ...
);

plot(Axes{2}, (0:sizeHS-1)*dx, grids_C_Si);
plotFormat( Axes{2}, ...
	strcat('Part of Silicon, then $T=', num2str(T),'K$, $N_{D}=', num2str(Nd), '\,1/m^{-3}$'), ...
	'z, $nm$', 'x, part of Si', ...
	strread(num2str(checkTime),'%s'), ...
	[0, (sizeHS-1)*dx], [], ...
	16 ...
);

figure('units', 'normalized', 'outerposition', [0 0 1 1]);
Axes = {
	subplot(1, 2, 1);
	subplot(1, 2, 2);
};

plot(Axes{1}, dU, [J(1, :); J(2, :); J(3, :); J(4, :)]);
plotFormat( Axes{1},...
	strcat('Current density, then $T=', num2str(T),'K$, $N_{D}=', num2str(Nd), '\,1/m^{-3}$'), ...
	'U, $V$', 'J, $A/m^{2}$', ...
	strread(num2str(checkTime(1:4)),'%s'), ...
	[], [0, max(max(J(1:2, :)))], ...
	16 ...
);

plot(Axes{2}, dU, J');
plotFormat( Axes{2}, ...
	strcat('Current density, then $T=', num2str(T),'K$, $N_{D}=', num2str(Nd), '\,1/m^{-3}$'), ...
	'U, $V$', 'J, $A/m^{2}$', ...
	strread(num2str(checkTime),'%s'), ...
	[], [0, max(max(J))], ...
	16 ...
);


outResult = 1
end