%% showResult: function description
function [outputs] = showResultSi(dx, HS, xAl, xSi, Title, checkTime)
	figure('units', 'normalized', 'outerposition', [0 0 1 1]);
	Axes = {
		subplot(1, 2, 1);
		subplot(1, 2, 2);
	};

	plot(Axes{1}, (0:HS-1)*dx, xAl);
	plotFormat( Axes{1}, ...
		strcat('Part of Aluminum in', Title) , ...
		'z, $nm$', 'x, part of Al', ...
		strread(num2str(checkTime),'%s'), ...
		[0, (HS-1)*dx], [], ...
		16 ...
	);

	plot(Axes{2}, (0:HS-1)*dx, xSi);
	plotFormat( Axes{2}, ...
		strcat('Part of Si in', Title) , ...
		'z, $nm$', 'x, part of Si', ...
		strread(num2str(checkTime),'%s'), ...
		[0, (HS-1)*dx], [], ...
		16 ...
	);
end