%% showResult: function description
function [outputs] = showResult(arg)
figure('units', 'normalized', 'outerposition', [0 0 1 1]);
Axes = {
	subplot(1, 2, 1);
	subplot(1, 2, 2);
};

plot(Axes{1}, (0:a+b+c+b+a-1)*dx, grids_C_Al);
plotFormat( Axes{1}, ...
	strcat('Part of Aluminum, then $T=', num2str(T),'K$') , ...
	'z, $nm$', 'x, part of Al', ...
	strread(num2str(checkTime),'%s'), ...
	[0, (a+b+c+b+a-1)*dx], [], ...
	16 ...
);

plot(Axes{2}, (0:a+b+c+b+a-1)*dx, grids_Ec);
plotFormat( Axes{2}, ...
	strcat('Part of Aluminum, then $T=', num2str(T),'K$'), ...
	'z, $nm$', 'x, part of Al', ...
	strread(num2str(checkTime),'%s'), ...
	[0, (a+b+c+b+a-1)*dx], [], ...
	16 ...
);

figure('units', 'normalized', 'outerposition', [0 0 1 1]);
Axes = {
	subplot(1, 2, 1);
   	subplot(1, 2, 2); 
};

plot(Axes{1}, dU, [J(1, :); J(2, :)]);
plotFormat( Axes{1},...
	strcat('Current density, then $T=', num2str(T),'K$'), ...
	'U, $V$', 'J, $A/m^{2}$', ...
	strread(num2str(checkTime(1:2)),'%s'), ...
	[], [0, max(max(J(1:2, :)))], ...
	16 ...
);

plot(Axes{2}, dU, J);
plotFormat( Axes{2}, ...
	strcat('Current density, then $T=', num2str(T),'K$'), ...
	'U, $V$', 'J, $A/m^{2}$', ...
	strread(num2str(checkTime),'%s'), ...
	[], [0, max(max(J))], ...
	16 ...
);
end