%% showResults: function description
function [outputs] = showResults(x, CInit, CAnalyt, CNumFRes, CNumBRes, CNumCNRes)

	figure('units', 'normalized', 'outerposition', [0 0 1 1]);
	Axes = {
		subplot(1, 4, 1);
		subplot(2, 4, 2);
		subplot(2, 4, 3);
		subplot(2, 4, 4);
		subplot(2, 4, 6);
		subplot(2, 4, 7);
		subplot(2, 4, 8);
	};
	
	plot(Axes{1},...
		x, CInit, ...
		x, CAnalyt, ...
		x, CNumFRes, '*', ...
		x, CNumBRes, '+', ...
		x, CNumCNRes, 'o'...
	);
	plotFormat( Axes{1}, ...
		'Check: Analytical, FTCS, BTCS, Crank-Nicolson', ...
		'x', 'Part', ...
		{'Initial data';
		'Analytical solve for $t_{1}$';
		'Analytical solve for $t_{2}$';
		'Numerical FTCS solve for $t_{1}$';
		'Numerical FTCS solve for $t_{2}$';
		'Numerical BTCS solve for $t_{1}$';
		'Numerical BTCS solve for $t_{2}$';
		'Numerical Crank-Nicolson solve for $t_{1}$';
		'Numerical Crank-Nicolson solve for $t_{2}$';
		}, ...
		[], [], ...
		10 ...
	);

	plot(Axes{2}, x, abs(CAnalyt - CNumFRes));
	plotFormat( Axes{2}, ...
		'abs(Analytical$-$FTCS)', ...
		'x', 'Difference', ...
		{'$t_{1}$'; '$t_{2}$'}, ...
		[], [], ...
		9 ...
	);
	
	plot(Axes{3}, x, abs(CAnalyt - CNumBRes));
	plotFormat( Axes{3}, ...
		'abs(Analytical$-$BTCS)', ...
		'x', 'Difference', ...
		{'$t_{1}$'; '$t_{2}$'}, ...
		[], [], ...
		9 ...
	);
	
	plot(Axes{4},x, abs(CAnalyt - CNumCNRes));
	plotFormat( Axes{4}, ...
		'abs(Analytical$-$Crank-Nicolson)', ...
		'x', 'Difference', ...
		{'$t_{1}$'; '$t_{2}$'}, ...
		[], [], ...
		9 ...
	);
	
	plot(Axes{5},x, abs(CNumBRes - CNumFRes));
	plotFormat( Axes{5}, ...
		'abs(FTCS$-$BTCS)', ...
		'x', 'Difference', ...
		{'$t_{1}$'; '$t_{2}$'}, ...
		[], [], ...
		9 ...
	);
	
	plot(Axes{6},x, abs(CNumBRes - CNumCNRes));
	plotFormat( Axes{6}, ...
		'abs(BTCS$-$Crank-Nicolson)', ...
		'x', 'Difference', ...
		{'$t_{1}$'; '$t_{2}$'}, ...
		[], [], ...
		9 ...
	);

	plot(Axes{7},x, abs(CNumFRes - CNumCNRes));
	plotFormat( Axes{7}, ...
		'abs(FTCS$-$Crank-Nicolson)', ...
		'x', 'Difference', ...
		{'$t_{1}$'; '$t_{2}$'}, ...
		[], [], ...
		9 ...
	);

	outputs = 1;